### ISSUE TITLE
unable to install on virtualbox

### ISSUE THREAD

**Issue by na1pir** [ubuntu-flashback/ubuntu-flashback-meta#1]
I guess iso image did not contain vmliuz image or it could not find it to copy it to target install hard drive.

**Comment by Mystic-Mirage** [comment]
Confirmed.

**Comment by Mystic-Mirage** [comment]
Images have been rebuilded. Try to install Ubuntu Flashback again with new download located in https://github.com/ubuntu-flashback/ubuntu-flashback-meta/releases/tag/16.04-beta1

**Comment by na1pir** [comment]
Install went through on virtual box. Great job! 

Then I tried to boot it from usb created with dd (and also with ubuntu's startup disc creator) on two laptops but it does not find boot sector. Tried two different sticks as well...

Finally I found last empty dvd in my house, burn it and finally it booted. I did have some problems creating swap partition... Manualy deleting all old partitions fixed that issue... 

Later there were some issues with "Software" installation tool. But I guess that will get fixed upstream. 

Gnome Flashback & xfce4 are only usefull desktop enviroments if you ask me. Please keep 'em comming:)

**Comment by Mystic-Mirage** [comment]
Thanks for your feedback!
